name: Atualizar Dados das Loterias

# Define quando essa ação vai rodar
on:
  schedule:
    # Roda todos os dias às 03:01 UTC (que equivale a 00:01 no horário de Brasília)
    - cron: '1 3 * * *'
  workflow_dispatch: # Permite rodar o script manualmente clicando em um botão no GitHub

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v3

      - name: Criar pasta de dados
        run: mkdir -p data

      - name: Fazer download das APIs e salvar em JSON local
        run: |
          curl -sL "https://loteriascaixa-api.herokuapp.com/api/megasena" -o data/megasena.json
          curl -sL "https://loteriascaixa-api.herokuapp.com/api/duplasena" -o data/duplasena.json
          curl -sL "https://loteriascaixa-api.herokuapp.com/api/lotofacil" -o data/lotofacil.json

      - name: Fazer o commit das alterações
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add data/*.json
          # O comando abaixo verifica se houve mudança nos dados. Se sim, faz o commit e o push.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Atualização diária dos resultados das loterias" && git push)
